spring:
  profiles:
    active: local
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/Game}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

