spring:
  profiles:
    active: local
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/Game}

server:
  error:
    include-exception: false
    include-stacktrace: never
    include-message: always
    include-binding-errors: always

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

